# Generated by Django 6.0.7 on 2026-07-20 16:46

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('business_number', models.CharField(blank=True, max_length=32, verbose_name='business number')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='contact name')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='credit limit')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='name (English)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'family',
                'verbose_name_plural': 'families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='barcode')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['warehouse', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='discount %')),
            ],
            options={
                'verbose_name': 'price tier',
                'verbose_name_plural': 'price tiers',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='profile number')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('description_en', models.CharField(blank=True, max_length=255, verbose_name='description (English)')),
                ('weight_g_per_m', models.PositiveIntegerField(blank=True, help_text='Grams per metre, as printed in the catalog.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='weight (g/m)')),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='catalog/sections/', verbose_name='cross-section drawing')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'warehouse',
                'verbose_name_plural': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_number', models.CharField(db_index=True, help_text='9-digit ID number (תעודת זהות). Used to sign in.', max_length=9, unique=True, validators=[core.models.validate_israeli_id], verbose_name='ID number')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\d\\-\\+\\s()]{7,20}$', message='Enter a valid phone number.')], verbose_name='phone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('role', models.CharField(choices=[('office', 'Office'), ('warehouse', 'Warehouse worker'), ('driver', 'Delivery driver'), ('client', 'Client'), ('manager', 'Manager')], default='warehouse', max_length=20, verbose_name='role')),
                ('language', models.CharField(choices=[('en', 'English'), ('he', 'Hebrew'), ('ar', 'Arabic')], default='he', max_length=5, verbose_name='language')),
                ('hired_on', models.DateField(blank=True, null=True, verbose_name='hired on')),
                ('emergency_contact', models.CharField(blank=True, max_length=150, verbose_name='emergency contact')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='emergency phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Can sign into Django admin.', verbose_name='admin access')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='order number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('picking', 'Picking'), ('ready', 'Ready for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='ordered at')),
                ('required_by', models.DateField(blank=True, null=True, verbose_name='required by')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.client', verbose_name='client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('loaded', 'Loaded'), ('en_route', 'En route'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('scheduled_for', models.DateField(blank=True, null=True, verbose_name='scheduled for')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('address', models.TextField(blank=True, verbose_name='delivery address')),
                ('recipient_name', models.CharField(blank=True, max_length=150, verbose_name='received by')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='deliveries/signatures/', verbose_name='signature')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='deliveries/photos/', verbose_name='proof photo')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliveries',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='price_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='core.pricetier', verbose_name='price tier'),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='name (English)')),
                ('manufacturer', models.CharField(default='Klil', max_length=100, verbose_name='manufacturer')),
                ('catalog_page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='catalog page')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='core.family', verbose_name='family')),
            ],
            options={
                'verbose_name': 'series',
                'verbose_name_plural': 'series',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_mm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='bar length (mm)')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='bars')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.order', verbose_name='order')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='core.profile', verbose_name='profile')),
                ('series', models.ForeignKey(blank=True, help_text='Which series this line was ordered for; a profile can serve several.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.series', verbose_name='series')),
            ],
            options={
                'verbose_name': 'order line',
                'verbose_name_plural': 'order lines',
            },
        ),
        migrations.CreateModel(
            name='SeriesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_header', models.CharField(blank=True, help_text='Sub-heading this row sits under, e.g. כנפיים – זיגוג עד 8 מ"מ', max_length=255, verbose_name='catalog group')),
                ('listed_description', models.CharField(blank=True, help_text='Only set when it differs from the profile description.', max_length=255, verbose_name='description as listed')),
                ('listed_weight_g_per_m', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='weight as listed (g/m)')),
                ('role', models.CharField(choices=[('frame', 'Frame'), ('sash', 'Sash'), ('track', 'Track'), ('mullion', 'Mullion'), ('glazing_bead', 'Glazing bead'), ('shutter', 'Shutter'), ('trim', 'Trim'), ('adapter', 'Adapter'), ('accessory', 'Accessory'), ('other', 'Other')], default='other', max_length=20, verbose_name='role')),
                ('glass_min_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='glass min (mm)')),
                ('glass_max_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='glass max (mm)')),
                ('track_count', models.PositiveSmallIntegerField(blank=True, help_text='For rails: 1–5 נתיבים.', null=True, verbose_name='tracks')),
                ('catalog_page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='catalog page')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_profiles', to='core.profile', verbose_name='profile')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_profiles', to='core.series', verbose_name='series')),
            ],
            options={
                'verbose_name': 'series profile',
                'verbose_name_plural': 'series profiles',
                'ordering': ['series', 'position'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='series',
            field=models.ManyToManyField(related_name='profiles', through='core.SeriesProfile', to='core.series', verbose_name='series'),
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_mm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='bar length (mm)')),
                ('finish', models.CharField(blank=True, help_text='Anodised, powder-coated RAL code, mill finish, etc.', max_length=100, verbose_name='finish')),
                ('minimum_quantity', models.PositiveIntegerField(default=0, help_text='Alert the office when quantity on hand drops below this.', verbose_name='reorder level')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='core.location', verbose_name='location')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='core.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'stock item',
                'verbose_name_plural': 'stock items',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receipt', 'Goods received'), ('pick', 'Picked for order'), ('return', 'Returned'), ('adjustment', 'Stock count adjustment'), ('transfer_in', 'Transferred in'), ('transfer_out', 'Transferred out'), ('scrap', 'Scrapped')], max_length=20, verbose_name='type')),
                ('quantity', models.IntegerField(help_text='Negative for outgoing movements.', verbose_name='bars')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='core.orderline', verbose_name='order line')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.stockitem', verbose_name='stock item')),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.warehouse', verbose_name='warehouse'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invoice', 'Invoice'), ('delivery_note', 'Delivery note'), ('quote', 'Quote'), ('credit_note', 'Credit note')], max_length=20, verbose_name='kind')),
                ('number', models.CharField(max_length=32, verbose_name='document number')),
                ('issued_at', models.DateField(verbose_name='issued at')),
                ('due_at', models.DateField(blank=True, null=True, verbose_name='due at')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='VAT')),
                ('is_paid', models.BooleanField(default=False, verbose_name='paid')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='PDF')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.client', verbose_name='client')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'number'), name='unique_document_number')],
            },
        ),
        migrations.AddIndex(
            model_name='seriesprofile',
            index=models.Index(fields=['series', 'role'], name='core_series_series__6ce84d_idx'),
        ),
        migrations.AddIndex(
            model_name='seriesprofile',
            index=models.Index(fields=['role', 'glass_max_mm'], name='core_series_role_9cf896_idx'),
        ),
        migrations.AddConstraint(
            model_name='seriesprofile',
            constraint=models.UniqueConstraint(fields=('series', 'profile', 'group_header', 'listed_description'), name='unique_profile_listing'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('profile', 'location', 'length_mm', 'finish'), name='unique_stock_item'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', '-created_at'], name='core_stockm_stock_i_e1250a_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_location_per_warehouse'),
        ),
    ]
