# Generated by Django 6.0.7 on 2026-07-20 17:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_type',
            field=models.CharField(choices=[('osek_patur', 'Osek Patur (עוסק פטור)'), ('osek_murshe', 'Osek Murshe (עוסק מורשה)'), ('company', 'Company (חברה בע"מ)'), ('partnership', 'Partnership (שותפות)'), ('nonprofit', 'Non-profit (עמותה)'), ('other', 'Other')], default='osek_murshe', max_length=20, verbose_name='business type'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='client',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Only if deliveries go somewhere other than the billing address.', verbose_name='delivery address'),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_name',
            field=models.CharField(blank=True, help_text='If it differs from the trading name.', max_length=200, verbose_name='registered legal name'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='postal code'),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, db_index=True, help_text='ח.פ. / ע.מ. — appears on every invoice.', max_length=32, verbose_name='tax ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_normalised',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='phone (normalised)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, verbose_name='billing address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='business_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='company registration number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='business name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, help_text='9-digit ID number (תעודת זהות). Staff sign in with this.', max_length=9, null=True, unique=True, validators=[core.models.validate_israeli_id], verbose_name='ID number'),
        ),
    ]
