# Generated by Django 6.0.7 on 2026-07-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_seriesprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesprofile',
            name='role',
            field=models.CharField(choices=[('frame', 'Frame'), ('sash', 'Sash'), ('track', 'Track'), ('mullion', 'Mullion'), ('glazing_bead', 'Glazing bead'), ('shutter', 'Shutter'), ('trim', 'Trim'), ('adapter', 'Adapter'), ('accessory', 'Accessory'), ('post', 'Post'), ('beam', 'Beam'), ('seal', 'Seal / gasket'), ('railing', 'Railing'), ('mesh', 'Insect screen'), ('panel', 'Panel'), ('other', 'Other')], default='other', max_length=20, verbose_name='role'),
        ),
    ]
