# Generated by Django 6.0.7 on 2026-07-31 16:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_shop_client_latitude_client_longitude_warehouse_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='discount %'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='VAT %'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='price per kg'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='total_length_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='total length (m)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='weight_kg_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='weight override (kg)'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='length_mm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='bar length (mm)'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='bars'),
        ),
    ]
