# Generated by Django 6.0.7 on 2026-07-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_orderline_unit_price_order_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='prepared',
            field=models.BooleanField(default=False, verbose_name='prepared'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='shortage_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='shortage note'),
        ),
    ]
