# Generated by Django 6.0.7 on 2026-07-31 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderline_prepared_orderline_shortage_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(verbose_name='clock in')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='clock out')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='worker')),
            ],
            options={
                'verbose_name': 'shift',
                'verbose_name_plural': 'shifts',
                'ordering': ['-clock_in'],
                'indexes': [models.Index(fields=['worker', '-clock_in'], name='core_shift_worker__628767_idx')],
            },
        ),
    ]
