# Generated by Django 6.0.7 on 2026-07-31 23:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='daily rate'),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_regular_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Hours before overtime starts; 8 for a 6-day week, 8.6 for 5-day.', max_digits=4, verbose_name='regular hours per day'),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='hourly rate'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='monthly salary'),
        ),
        migrations.AddField(
            model_name='user',
            name='overtime_enabled',
            field=models.BooleanField(default=True, verbose_name='pay overtime'),
        ),
        migrations.AddField(
            model_name='user',
            name='pay_basis',
            field=models.CharField(choices=[('hourly', 'By hour'), ('daily', 'By day'), ('monthly', 'Monthly salary')], default='hourly', max_length=10, verbose_name='pay basis'),
        ),
    ]
