# Generated by Django 6.0.7 on 2026-08-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_daily_rate_user_daily_regular_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_cloud_name', models.CharField(blank=True, max_length=100, verbose_name='Cloudinary cloud name')),
                ('cloudinary_api_key', models.CharField(blank=True, max_length=100, verbose_name='Cloudinary API key')),
                ('cloudinary_api_secret', models.CharField(blank=True, max_length=200, verbose_name='Cloudinary API secret')),
            ],
            options={
                'verbose_name': 'app configuration',
                'verbose_name_plural': 'app configuration',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='registered legal name'),
        ),
        migrations.AddField(
            model_name='shop',
            name='tax_id',
            field=models.CharField(blank=True, help_text='ח.פ. / ע.מ. — appears on order and delivery documents.', max_length=32, verbose_name='tax ID'),
        ),
    ]
