# Generated by Django 6.0.7 on 2026-08-01 11:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_appconfig_shop_legal_name_shop_tax_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('month', models.PositiveSmallIntegerField(verbose_name='month')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Finalised')], default='draft', max_length=10, verbose_name='status')),
                ('source', models.CharField(choices=[('generated', 'Generated'), ('manual', 'Manual')], default='generated', max_length=10, verbose_name='source')),
                ('pay_basis', models.CharField(choices=[('hourly', 'By hour'), ('daily', 'By day'), ('monthly', 'Monthly salary')], default='hourly', max_length=10, verbose_name='pay basis')),
                ('overtime_enabled', models.BooleanField(default=True, verbose_name='overtime paid')),
                ('days_worked', models.PositiveSmallIntegerField(default=0, verbose_name='days worked')),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='regular hours')),
                ('overtime_125_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='overtime 125% hours')),
                ('overtime_150_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='overtime 150% hours')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='hourly rate')),
                ('base_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='base pay')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='overtime pay')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='payslips/', verbose_name='PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('finalised_at', models.DateTimeField(blank=True, null=True, verbose_name='finalised at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL, verbose_name='worker')),
            ],
            options={
                'verbose_name': 'payslip',
                'verbose_name_plural': 'payslips',
                'ordering': ['-year', '-month', 'worker__last_name'],
            },
        ),
        migrations.CreateModel(
            name='PayslipAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive to add (bonus, travel), negative to deduct (advance).', max_digits=12, verbose_name='amount')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='core.payslip', verbose_name='payslip')),
            ],
            options={
                'verbose_name': 'payslip adjustment',
                'verbose_name_plural': 'payslip adjustments',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('worker', 'year', 'month'), name='unique_payslip_period'),
        ),
    ]
