# Generated by Django 6.0.7 on 2026-08-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_payslip_payslipadjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_note_pdf',
            field=models.FileField(blank=True, null=True, upload_to='orders/', verbose_name='delivery note PDF'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_note_pdf',
            field=models.FileField(blank=True, null=True, upload_to='orders/', verbose_name='order note PDF'),
        ),
    ]
