# Generated by Django 6.0.7 on 2026-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_delivery_note_pdf_order_order_note_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop/', verbose_name='logo'),
        ),
    ]
