# Generated by Django 6.0.7 on 2026-08-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_shop_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivery signed at'),
        ),
    ]
