# Generated by Django 6.0.7 on 2026-08-07 19:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_delivery_signed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='accountant_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='accountant email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='accountant_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='accountant name'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='accountant_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='accountant phone'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='greeninvoice_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Green Invoice API key'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='greeninvoice_api_secret',
            field=models.CharField(blank=True, max_length=200, verbose_name='Green Invoice API secret'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='OpenAI API key'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='smtp_from',
            field=models.EmailField(blank=True, max_length=254, verbose_name='SMTP from address'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP host'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP password'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SMTP port'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='SMTP use TLS'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP username'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10, verbose_name='direction')),
                ('number', models.CharField(blank=True, max_length=64, verbose_name='invoice number')),
                ('party_name', models.CharField(blank=True, max_length=200, verbose_name='party name')),
                ('party_tax_id', models.CharField(blank=True, max_length=32, verbose_name='party tax ID')),
                ('issued_at', models.DateField(verbose_name='issued at')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='category')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal')),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='VAT')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generated'), ('scanned', 'Scanned')], default='manual', max_length=12, verbose_name='source')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10, verbose_name='status')),
                ('allocation_number', models.CharField(blank=True, max_length=64, verbose_name='allocation number')),
                ('external_id', models.CharField(blank=True, max_length=64, verbose_name='external id')),
                ('file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='file')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-issued_at', '-id'],
            },
        ),
    ]
