# Generated by Django 6.0.7 on 2026-08-07 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_appconfig_accountant_email_appconfig_accountant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.order', verbose_name='order'),
        ),
    ]
