# Generated by Django 6.0.7 on 2026-08-07 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_invoice_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='work date')),
                ('requested_clock_in', models.DateTimeField(blank=True, null=True, verbose_name='requested clock in')),
                ('requested_clock_out', models.DateTimeField(blank=True, null=True, verbose_name='requested clock out')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('review_note', models.CharField(blank=True, max_length=255, verbose_name='review note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests', to='core.shift', verbose_name='shift')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to=settings.AUTH_USER_MODEL, verbose_name='worker')),
            ],
            options={
                'verbose_name': 'shift correction request',
                'verbose_name_plural': 'shift correction requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
