# Generated by Django 6.0.7 on 2026-08-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_shiftcorrectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='public_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='public token'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('picking', 'Picking'), ('ready', 'Ready for delivery'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
