# Generated by Django 6.0.7 on 2026-08-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_invoice_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='delivered_length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='delivered length (m)'),
        ),
    ]
