# Generated by Django 6.0.7 on 2026-08-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_default_series_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location_url',
            field=models.URLField(blank=True, help_text='Paste a link from Google Maps, Waze or Apple Maps. The delivery point is taken from it.', max_length=500, verbose_name='map link'),
        ),
    ]
