# Generated by Django 6.0.7 on 2026-08-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_client_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text='The person who signed, for sending them the delivery note.', max_length=32, verbose_name="recipient's phone"),
        ),
    ]
