# Generated by Django 6.0.7 on 2026-08-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_delivery_recipient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='mapbox_token',
            field=models.CharField(blank=True, help_text='Public token (pk.…) for the map. A MAPBOX_TOKEN environment variable overrides this.', max_length=255, verbose_name='Mapbox token'),
        ),
    ]
