# Generated by Django 6.0.7 on 2026-08-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_appconfig_mapbox_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='register_code',
            field=models.CharField(blank=True, help_text='Anyone with this code can create a manager account. Leave empty to switch manager registration off. A REGISTER_CODE environment variable overrides this.', max_length=128, verbose_name='manager register code'),
        ),
    ]
