# Generated by Django 6.0.7 on 2026-08-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='auto_closed',
            field=models.BooleanField(db_index=True, default=False, help_text='System closed a shift the worker forgot to clock out of.', verbose_name='auto-closed'),
        ),
    ]
