# Generated by Django 6.0.7 on 2026-09-02 06:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_shift_auto_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cutting_list', 'Cutting list'), ('drawing', 'Drawing'), ('other', 'Other')], default='drawing', max_length=20, verbose_name='kind')),
                ('file', models.FileField(upload_to='order-attachments/', verbose_name='file')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='original name')),
                ('note', models.CharField(blank=True, help_text='Which drawing or elevation this sheet covers.', max_length=255, verbose_name='note')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.order', verbose_name='order')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_attachments', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'order attachment',
                'verbose_name_plural': 'order attachments',
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('transfer', 'Bank transfer'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20, verbose_name='method')),
                ('paid_on', models.DateField(verbose_name='paid on')),
                ('due_on', models.DateField(blank=True, help_text='For a post-dated cheque: when it can be banked.', null=True, verbose_name='due on')),
                ('reference', models.CharField(blank=True, help_text='Cheque number, transfer reference, receipt number.', max_length=80, verbose_name='reference')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.invoice', verbose_name='invoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.order', verbose_name='order')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-paid_on', '-id'],
            },
        ),
    ]
