# Generated by Django 6.0.7 on 2026-09-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_order_money_and_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('quote', 'Quote'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('picking', 'Picking'), ('ready', 'Ready for delivery'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
