# Generated by Django 6.0.7 on 2026-09-02 06:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Off this line, before any discount on the order.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='discount %'),
        ),
    ]
