# Generated by Django 6.0.7 on 2026-09-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_line_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='accepted at'),
        ),
        migrations.AddField(
            model_name='order',
            name='quoted_as',
            field=models.CharField(blank=True, max_length=32, verbose_name='quoted as'),
        ),
    ]
