# Generated by Django 6.0.7 on 2026-09-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_quote_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='quote_valid_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Aluminium moves. A quote says how long the price holds.', verbose_name='quote valid for (days)'),
        ),
    ]
