# Generated by Django 6.0.7 on 2026-09-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_quote_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderattachment',
            name='kind',
            field=models.CharField(choices=[('drawing', 'Drawing'), ('other', 'Other')], default='drawing', max_length=20, verbose_name='kind'),
        ),
    ]
