# Generated by Django 6.0.7 on 2026-09-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_seed_missing_catalogues'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='latest_android_build',
            field=models.PositiveIntegerField(blank=True, help_text='The build number (13 in 1.1.0+13). This is what is compared.', null=True, verbose_name='current phone build'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='latest_android_url',
            field=models.URLField(blank=True, verbose_name='phone download link'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='latest_android_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='current phone version'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='latest_desktop_url',
            field=models.URLField(blank=True, help_text='Where the installer can be downloaded.', verbose_name='desktop download link'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='latest_desktop_version',
            field=models.CharField(blank=True, help_text='e.g. 1.1.0. Leave empty and the app never mentions updates.', max_length=20, verbose_name='current desktop version'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='release_notes',
            field=models.TextField(blank=True, help_text='Shown with the update notice. One or two lines is plenty.', verbose_name='what is new'),
        ),
    ]
