# Generated by Django 6.0.7 on 2026-09-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_app_release_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='public_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='public token'),
        ),
    ]
